### PR TITLE
Automate Midas ontology release pipeline

### PR DESCRIPTION
**Pull request by matentzn**
replaces #45 

You basically have to merge this @hoganwr then go to the repo settings, and in the repos setting, allow actions to write information:

image

I don't know if the pipeline will run all by itself the moment you merge, lets see.

After that every time the edit file or an import changes, the release pipeline is triggered.

If you want to test it in a safer environment:

Use your fork!

### CODE REVIEW

**Comment by hoganwr** [comment]
Nico, Thanks!  I tried it in my fork and it works. I also made an edit on
your fork (sorry about that), and because there was already a release it
failed. So one thing to note is to only edit once per day.  We don't update
this file that much so one edit session per day is fine.

**Comment by matentzn** [comment]
Exactly, this is the downside of this approach! If it turns out to be an issue, you can also simply reactive the automation and have it, instead, be triggered manually by the click of a two buttons (on https://github.com/midas-network/midas-data/actions, you would click on the workflow and on "Run Workflow"). I would try to see how you get on with the automated system for now!

**Comment by hoganwr** [comment]
I think just basic release workflow documentation, and the usual place: markdown files in src/docs?  Does that sound ok?

**Comment by matentzn** [comment]
Ok you can merge this here, I will provide documentation in a separate PR.

**Pull request merged**
