### PR TITLE
First draft Midas Makefile

### PR DESCRIPTION
**Pull request by matentzn**
This is half way what we discussed @hoganwr, but do not merge yet, we still need:

1. documentation
2. Github action for automated releases

### CODE REVIEW

**Comment by hoganwr** [comment]
Nico, just following up on this. How can I help w/documentation and Github action for auto release?

**Comment by matentzn** [comment]
@hoganwr, I have entirely automated the whole process now. 

If you agree with this, I put it into action:

1. If someone updates the edit file, or an import, a versioned release is created immediately
2. It works like this: 
   1. change is committed to master.
   2. Action recognises change, refreshes imports and rebuilds release files.
   3. Action pushes changes automatically to `main` branch
   4. Action automatically creates a tagged, versioned release

How does this sound? No human in the loop at all.

**Comment by hoganwr** [comment]
Nico, that's fantastic!  Ok if I try it out?

**Comment by matentzn** [comment]
Closing in favour of #46

**Pull request closed without merging**
